import "./styles/globals.css";
export const metadata = {
  title: "Arthur Guilherme ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" max-w-[100rem] mx-auto">
      <body>{children}</body>
    </html>
  );
}
